=== hradecek/hw_pb138/hw02/company.xsd
<?xml version="1.0" encoding="utf-8"?>

<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

    <!-- definition of simple types -->            
    <!-- string types -->       
    <xsd:simpleType name="nameType"> <!-- Need to be valid also for names: van Damme, d'Alambert, Ce-tung ... -->
        <xsd:restriction base="xsd:string">            
            <xsd:pattern value="\p{Lu}\p{Ll}+( |([\p{Lu}\p{Ll}]')?|(\p{Lu}?\p{Ll}+-?)*)*" /> 
        </xsd:restriction>
    </xsd:simpleType>    

    <xsd:simpleType name="descriptionType">
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="\p{Lu}\p{L}*( \p{L}+)*" />
        </xsd:restriction>
    </xsd:simpleType>
        
    <xsd:simpleType name="nonEmptyANStrType"> <!-- non empty *A*lpha *N*umeric string -->
        <xsd:restriction base="xsd:string">            
            <xsd:pattern value="[a-zA-Z0-9]+( [a-zA-Z0-9]+)*" />
        </xsd:restriction>
    </xsd:simpleType>
        
    <xsd:simpleType name="nonEmptyNWStrType"> <!-- non empty *No* *W*hitespaces string -->
        <xsd:restriction base="xsd:string">
            <!-- <xsd:minLength value="1" /> -->                        
            <xsd:pattern value="(\p{L}_?)+" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <!-- numeric types -->
    <xsd:simpleType name="positiveRealType">
        <xsd:restriction base="xsd:decimal">
            <xsd:minExclusive value="0.00" />
            <xsd:pattern value="[1-9]\d*\.\d{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="nonNegativeRealType">
        <xsd:restriction base="xsd:decimal">            
            <xsd:minInclusive value="0.00" />
            <xsd:pattern value="0\.\d{2}" />
            <xsd:pattern value="[1-9]\d*\.\d{2}" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="negativeRealType">
        <xsd:restriction base="xsd:decimal">
            <xsd:maxExclusive value="0.00" />
            <xsd:pattern value="-?[1-9]\d*\.\d{2}" />
        </xsd:restriction>
    </xsd:simpleType>        
    
    <!-- definition of groups -->
    <xsd:group name="productionServiceGroup">
        <xsd:sequence>
            <xsd:element name="name" type="nonEmptyANStrType" />
            <xsd:element name="costs" type="negativeRealType" />
            <xsd:element name="price" type="nonNegativeRealType" />            
        </xsd:sequence>
    </xsd:group>
    
    <xsd:group name="productionCommodityGroup">
        <xsd:sequence>
            <xsd:element name="description" type="descriptionType" />
            <xsd:choice>
                <xsd:element name="price" type="nonNegativeRealType" />
                <xsd:element name="costs" type="negativeRealType" />
            </xsd:choice>
        </xsd:sequence>        
    </xsd:group>
    
    <!-- definition of complex types -->
    <xsd:complexType name="companyType">     
        <xsd:sequence>        
            <xsd:element name="division" type="divisionType" minOccurs="1" maxOccurs="unbounded" />                                            
        </xsd:sequence>        
    </xsd:complexType>
   
    <xsd:complexType name="divisionType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" minOccurs="0" />
            <xsd:element name="head" type="headType" minOccurs="0" />            
            <xsd:element name="products" type="productsType" minOccurs="0" />
        </xsd:sequence>       
        <xsd:attribute name="did" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="headType">
        <xsd:sequence>
            <xsd:element name="person" type="personType" minOccurs="1" />                            
        </xsd:sequence>
    </xsd:complexType>
          
    <xsd:complexType name="personType">         
        <xsd:sequence>        
            <xsd:element name="name" type="nameType" minOccurs="1" />
            <xsd:element name="surname" type="nameType" minOccurs="1" />
            <xsd:element name="salary" type="positiveRealType" minOccurs="1" />
            <xsd:element name="note" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />        
        </xsd:sequence>                 
        <xsd:attribute name="pid" type="xsd:positiveInteger" use="required" />   
    </xsd:complexType>

    <xsd:complexType name="productsType">
        <xsd:sequence>
            <xsd:element name="product" type="productType" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>        
    </xsd:complexType>            
        
    <xsd:complexType name="productType">        
        <xsd:choice minOccurs="1" maxOccurs="unbounded" >            
            <xsd:group ref="productionCommodityGroup" />
            <xsd:group ref="productionServiceGroup" />
        </xsd:choice>
        <xsd:attribute name="category" type="nonEmptyNWStrType" use="required" />
    </xsd:complexType>    
         
    <!-- ROOT -->   
    <xsd:element name="company" type="companyType">    
        <xsd:unique name="pidUnique">
            <xsd:selector xpath="division/head/person" />
            <xsd:field xpath="@pid" />
        </xsd:unique>
        <xsd:unique name="didUnique">
            <xsd:selector xpath="division" />
            <xsd:field xpath="@did" />
        </xsd:unique>
    </xsd:element>
    
</xsd:schema>

=== hradecek/hw_pb138/hw02/src/company-tomp.xml
<?xml version="1.0" encoding="utf-8"?>

<company 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="company.xsd">
    
    <!-- did is required, a nonempty string unique for all divisions 
    (can be used as a key for divisions) -->
    <division did="production_zlin">
        <!-- name is optional and contains a string -->
        <name>Production factory Zlín</name>
        <!-- head is optional and contains always a person if present -->
        <head>
            <!-- pid is required, unique (positive) integer 
            (can be used as a key for persons);
            the name, surname, salary elts. can be ordered in any order -->
            <person pid="1"> 	
                <!-- name is required, non-empty string -->	 
                <name>Pavel</name>	 
                <!-- surname is required, non-empty string -->
                <surname>Novák</surname> 
                <!-- salary is required, positive number 
	             with 2 decimal places precision, e.g. 10000.50 -->
                <salary>20000.00</salary> 
                <!-- note optional element, repeatable, contains any string -->  
                <note>Poznámka</note>   
            </person>            
        </head>
        <products><!-- optional element, products of the division. Must contain one or more 
                    elements product-->
            <product category="ICBM"> <!-- Division Commodity 
                                      category is required, contains non-empty string without 
                                      whitespace(s)-->
                <name>Šipečka</name> <!-- name of the comodity, alfa numeric string, 
                                          must begin with a letter, it may contain whitespace(s) -->
                <costs>-10000.00</costs> <!-- production costs of the commodity, mansdatory element,
                                             negative number with 2 decimal places precision -->
                <price>110000.00</price> <!-- price of the commodity, mandatory element,
                                             possitive number with 2 decimal places precision -->
            </product>
            <product category="ICBMInstallation"> <!-- Divisioin service -->
                <description>Installation of Šipečka</description>
                                            <!-- Description of a service - mandatory element
                                                contains only letters and whitespace(s)-->
                <price>10000.00</price>     <!-- Price of the service, either 
                                                 price or costs must be included, for 
                                                 content see commodity-->
            </product>
        </products>
    </division>
    <division did="development_brno">
        <head>
            <person pid="2">
                <name>Jan</name>
                <surname>Novák</surname>
                <salary>200000.00</salary>
            </person>
        </head>
        <products>
            <product category="missile_development">
                <description>Development of new missiles</description>
                <costs>-100000.00</costs>
            </product>
        </products>
    </division>
</company>
